[package]
name = "espr-derive"
version = "0.4.0"
edition = "2021"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>", "Toshiki Teramura <teramura@ricos.co.jp"]
rust-version = "1.75.0"

description   = "Procedual macro for running espr compiler"
documentation = "https://ricosjp.github.io/ruststep/espr_derive/index.html"
repository    = "https://github.com/ricosjp/ruststep"
keywords      = ["step", "cad", "compiler", "proc-macro"]
license       = "Apache-2.0"
readme        = "../README.md"
categories    = ["science", "development-tools"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
proc-macro2 = "1.0.86"
syn = { version = "2.0.77", features = ["full", "extra-traits"] }

[dependencies.espr]
version = "0.4.0"
path = "../espr"

[dev-dependencies]
ruststep = { version = "0.4.0", path = "../ruststep" }
ruststep-derive = { version = "0.4.0", path = "../ruststep-derive" }
serde = "1.0.210"
derive-new = "0.5.9"
